---
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/mikeybabs/GhostDB:/bitnami
  ghost:
    image: bitnami/ghost:latest
    depends_on:
      - mariadb
    ports:
      - '80:2368'
    volumes:
      - /home/mikeybabs/Ghost:/bitnami
